// ============================================================
// OTF Export — DottFont Generator
//
// Builds and downloads a .otf font file containing all characters
// defined in dinish-bold-metrics.json, using opentype.js.
//
// Each glyph is generated by running the full dot-generation pipeline
// (renderTextMask + drawMeshGradientPreview) on a single character,
// then mapping canvas dot positions to font coordinate space.
//
// Font metrics (UPM, ascender, descender) and per-glyph advance widths
// are read from dinish-bold-metrics.json. BASELINE_Y is still measured
// from the canvas at runtime to match the browser's actual rendering.
//
// Coordinate mapping:
//   fontX = (canvasX - PADDING) * SCALE
//   fontY = (BASELINE_Y - canvasY) * SCALE
//
// Depends on globals from script-generator_DottFont.js:
//   presenceStrength, sizeMultiplier, tailleGenerationMultiplier,
//   currentShape, DOT_SPACING, PADDING, FONT_SIZE, MAX_RADIUS, MIN_RADIUS,
//   gCtx, renderTextMask, drawMeshGradientPreview, generate
// ============================================================

const exportOtfBtn = document.getElementById('export-otf-btn');

// Appends a cubic-bezier circle approximation to an opentype.js Path.
// Uses the standard constant k≈0.5523 for a 4-arc circle.
// Font coordinate space: Y-axis points up.
function addCircleToPath(path, cx, cy, r) {
  const k = 0.5523;
  path.moveTo(cx,         cy + r);
  path.curveTo(cx + k*r, cy + r,  cx + r, cy + k*r,  cx + r, cy);
  path.curveTo(cx + r,   cy - k*r, cx + k*r, cy - r,  cx,     cy - r);
  path.curveTo(cx - k*r, cy - r,  cx - r, cy - k*r,  cx - r, cy);
  path.curveTo(cx - r,   cy + k*r, cx - k*r, cy + r,  cx,     cy + r);
  path.close();
}

// Appends a square (axis-aligned) to an opentype.js Path.
// halfSize is half the side length.
function addSquareToPath(path, cx, cy, halfSize) {
  const s = halfSize;
  path.moveTo(cx - s, cy + s);
  path.lineTo(cx + s, cy + s);
  path.lineTo(cx + s, cy - s);
  path.lineTo(cx - s, cy - s);
  path.close();
}

// Appends an ellipse to an opentype.js Path.
// Same logic as addCircleToPath but with independent rx and ry.
// From ellipse.svg viewBox (2 × 2.75): the square <use> bounding box constrains
// the taller axis, so ry = fr and rx = fr × (2 / 2.75).
function addEllipseToPath(path, cx, cy, rx, ry) {
  const kx = 0.5523 * rx;
  const ky = 0.5523 * ry;
  path.moveTo(cx,       cy + ry);
  path.curveTo(cx + kx, cy + ry,  cx + rx, cy + ky,  cx + rx, cy);
  path.curveTo(cx + rx, cy - ky,  cx + kx, cy - ry,  cx,      cy - ry);
  path.curveTo(cx - kx, cy - ry,  cx - rx, cy - ky,  cx - rx, cy);
  path.curveTo(cx - rx, cy + ky,  cx - kx, cy + ry,  cx,      cy + ry);
  path.close();
}

// Appends a horizontal pill (stadium) shape to an opentype.js Path.
// From trait.svg viewBox (3.614 × 1.7): halfW = fr, halfH = fr × (1.7 / 3.614).
// Corner radius equals halfH, making perfect semicircles at each end.
function addTraitToPath(path, cx, cy, halfW, halfH) {
  const kh = 0.5523 * halfH;
  const rx = halfW - halfH;
  path.moveTo(cx - rx,       cy + halfH);
  path.lineTo(cx + rx,       cy + halfH);
  path.curveTo(cx + rx + kh, cy + halfH,  cx + halfW, cy + kh,  cx + halfW, cy);
  path.curveTo(cx + halfW,   cy - kh,     cx + rx + kh, cy - halfH, cx + rx, cy - halfH);
  path.lineTo(cx - rx,       cy - halfH);
  path.curveTo(cx - rx - kh, cy - halfH,  cx - halfW, cy - kh,  cx - halfW, cy);
  path.curveTo(cx - halfW,   cy + kh,     cx - rx - kh, cy + halfH, cx - rx, cy + halfH);
  path.close();
}

// Appends a ring (donut) to an opentype.js Path.
// Outer circle CW + inner circle CCW → hole via non-zero winding rule (CFF/OTF).
// From circle_outline.svg viewBox (2.314 × 2.314): outerR = fr, innerR = fr × (0.758 / 1.157).
function addCircleOutlineToPath(path, cx, cy, outerR, innerR) {
  const k = 0.5523;
  path.moveTo(cx,             cy + outerR);
  path.curveTo(cx + k*outerR, cy + outerR,  cx + outerR, cy + k*outerR,  cx + outerR, cy);
  path.curveTo(cx + outerR,   cy - k*outerR, cx + k*outerR, cy - outerR, cx,          cy - outerR);
  path.curveTo(cx - k*outerR, cy - outerR,  cx - outerR, cy - k*outerR,  cx - outerR, cy);
  path.curveTo(cx - outerR,   cy + k*outerR, cx - k*outerR, cy + outerR, cx,          cy + outerR);
  path.close();
  path.moveTo(cx,             cy + innerR);
  path.curveTo(cx - k*innerR, cy + innerR,  cx - innerR, cy + k*innerR,  cx - innerR, cy);
  path.curveTo(cx - innerR,   cy - k*innerR, cx - k*innerR, cy - innerR, cx,          cy - innerR);
  path.curveTo(cx + k*innerR, cy - innerR,  cx + innerR, cy - k*innerR,  cx + innerR, cy);
  path.curveTo(cx + innerR,   cy + k*innerR, cx + k*innerR, cy + innerR, cx,          cy + innerR);
  path.close();
}

// Builds and downloads an OTF font for all characters defined in
// dinish-bold-metrics.json. Font metrics and advance widths come from
// the JSON; BASELINE_Y is measured from the canvas at runtime.
async function exportOTF() {
  exportOtfBtn.textContent = 'En cours...';
  exportOtfBtn.disabled = true;

  // Load font metrics and glyph data from JSON.
  // Provides UPM, ascender, descender, and per-glyph advance widths.
  let metrics;
  try {
    const res = await fetch('source_export_otf/dinish-bold-metrics.json');
    metrics = await res.json();
  } catch (e) {
    console.error('Failed to load dinish-bold-metrics.json:', e);
    exportOtfBtn.textContent = 'Erreur JSON';
    exportOtfBtn.disabled = false;
    return;
  }

  const UPM       = metrics.units.upm;
  const ASCENDER  = metrics.fontMetrics.ascender;
  const DESCENDER = metrics.fontMetrics.descender;

  // Measure the alphabetic baseline position in canvas pixels.
  // Strategy: measure 'A' with textBaseline='top' (same as renderTextMask) and use
  // actualBoundingBoxDescent. Since 'A' has yMin=0 (sits exactly on the alphabetic
  // baseline), actualBoundingBoxDescent = distance from the 'top' reference point
  // down to the baseline. This value is always positive and consistent across browsers.
  //
  // Why not fontBoundingBoxAscent? Returns the font-wide ascender (≈1050/1024*px),
  // which is larger than the actual 'top'-to-baseline distance → glyphs shift +211u.
  // Why not alphabeticBaseline? The Canvas spec uses upward-positive convention, so
  // alphabeticBaseline with textBaseline='top' returns a negative number in Chrome/FF
  // → BASELINE_Y = PADDING + negative = too small → glyphs shift into negative y.
  // ctx is the global hidden-canvas context defined in script-generator_DottFont.js
  ctx.font         = `700 ${FONT_SIZE}px DINish, sans-serif`;
  ctx.textBaseline = 'top';
  const measured   = ctx.measureText('A');
  const BASELINE_Y = PADDING + measured.actualBoundingBoxDescent;
  const SCALE      = UPM / FONT_SIZE;  // canvas px → font units

  // Charset is driven by the JSON — only characters with defined metrics are exported.
  const CHARSET = Object.keys(metrics.glyphs);

  // PostScript glyph names for non-letter characters.
  // Letters and accented letters use the character itself as the PostScript name.
  // Special characters must be mapped to valid PS identifiers (no raw symbols allowed).
  const GLYPH_NAMES = {
    '0':'zero',        '1':'one',         '2':'two',        '3':'three',     '4':'four',
    '5':'five',        '6':'six',         '7':'seven',      '8':'eight',     '9':'nine',
    '.':'period',      '?':'question',    ':':'colon',      ',':'comma',      ';':'semicolon',
    '!':'exclam',      '#':'numbersign',  '$':'dollar',     '%':'percent',   '&':'ampersand',
    "'": 'quotesingle','(':'parenleft',   ')':'parenright', '+':'plus',      '*':'asterisk',
    '-':'hyphen',      '_':'underscore',  '/':'slash',      '\\':'backslash','ß':'germandbls',
    '@':'at',          '<':'less',        '>':'greater',    '"':'quotedbl'
  };

  const glyphs = [];

  // .notdef — required as the first glyph in any valid OTF
  glyphs.push(new opentype.Glyph({
    name: '.notdef', unicode: 0, advanceWidth: 500, path: new opentype.Path()
  }));

  // space — gives kerning/layout tools a working word-break glyph
  glyphs.push(new opentype.Glyph({
    name: 'space', unicode: 32, advanceWidth: 222, path: new opentype.Path()
  }));

  // One glyph per character present in the JSON
  for (const char of CHARSET) {
    // Run the full render pipeline for this single character
    const { canvasW, canvasH } = renderTextMask(char);
    // Pass canvasH as refWidth so the gradient x-axis uses a fixed reference (FONT_SIZE + 2*PADDING)
    // identical for every character, eliminating per-character gradient remapping and the resulting trembling.
    drawMeshGradientPreview(canvasW, canvasH, undefined, canvasH);

    const step      = DOT_SPACING * tailleGenerationMultiplier;
    const imageData = gCtx.getImageData(0, 0, canvasW, canvasH);
    const pixels    = imageData.data;
    const path      = new opentype.Path();

    for (let y = step / 2; y < canvasH; y += step) {
      for (let x = step / 2; x < canvasW; x += step) {
        const i          = (Math.floor(y) * canvasW + Math.floor(x)) * 4;
        const brightness = (pixels[i] + pixels[i+1] + pixels[i+2]) / 3;
        if (brightness >= 245) continue;

        // Apply the same probabilistic filter as the SVG output
        const probability = Math.max(0, 1 - (brightness / 204) * presenceStrength * 2);
        if (Math.random() > probability) continue;

        const darkness = Math.max(0, 1 - brightness / 204);
        const radius   = (MIN_RADIUS + darkness * (MAX_RADIUS - MIN_RADIUS)) * sizeMultiplier * tailleGenerationMultiplier;

        // Map canvas px → font units, flipping Y axis.
        // Round cx/cy to integers to avoid float-to-int rounding drift in opentype.js:
        // a non-integer step (e.g. 4.8px → 32.77 font units) would otherwise cause
        // alternating 32/33-unit gaps, producing visible trembling in the exported OTF.
        const fx = Math.round((x - PADDING) * SCALE);
        const fy = Math.round((BASELINE_Y - y) * SCALE);
        const fr = radius * SCALE;

        if (currentShape === 'square') {
          addSquareToPath(path, fx, fy, fr);
        } else if (currentShape === 'ellipse') {
          addEllipseToPath(path, fx, fy, fr * (2 / 2.75), fr);
        } else if (currentShape === 'trait') {
          addTraitToPath(path, fx, fy, fr, fr * (1.7 / 3.614));
        } else if (currentShape === 'circle_outline') {
          addCircleOutlineToPath(path, fx, fy, fr, fr * (0.758 / 1.157));
        } else {
          addCircleToPath(path, fx, fy, fr);
        }
      }
    }

    const name = GLYPH_NAMES[char] || char;
    glyphs.push(new opentype.Glyph({
      name,
      unicode:      char.codePointAt(0),
      advanceWidth: metrics.glyphs[char].advanceWidth,
      path
    }));
  }

  const font = new opentype.Font({
    familyName:     'DottFont',                                                          
    styleName:      'Regular',                                                          
    unitsPerEm:     UPM,
    ascender:       ASCENDER,
    descender:      DESCENDER,
    copyright:      '© 2026 Zoé Berthelot',                                           
    manufacturer:   'Flutgraben e.V.',                                                  
    designer:       'Zoé Berthelot @Neutronzoo',                                                          
    version:        'Version 1.000',                                                     
    description:    'Generated with DottFont Generator',                                 
    license:        'This Font Software is licensed under the SIL Open Font License, Version 1.1.', 
    licenseURL:     'https://scripts.sil.org/OFL',                                       
    glyphs
  });

  // Build filename from current settings: shape_tailleGeneration_size_presence
  const filename = `${currentShape}_${tailleGenerationMultiplier.toFixed(2)}_${sizeMultiplier.toFixed(2)}_${presenceStrength.toFixed(2)}.otf`;
  font.download(filename);

  // Restore the display to the current text input after processing
  generate();
  exportOtfBtn.textContent = 'OTF';
  exportOtfBtn.disabled = false;
}

// OTF export button — builds the font on click
exportOtfBtn.addEventListener('click', exportOTF);
