// ============================================================
// OTF Export — DottFont Generator
//
// Builds and downloads a .otf font file containing the 42-character
// charset (A–Z, 0–9, punctuation) using opentype.js.
//
// Each glyph is generated by running the full dot-generation pipeline
// (renderTextMask + drawMeshGradientPreview) on a single character,
// then mapping canvas dot positions to font coordinate space.
//
// Depends on globals from script-generator_DottFont.js:
//   presenceStrength, sizeMultiplier, tailleGenerationMultiplier,
//   currentShape, DOT_SPACING, PADDING, FONT_SIZE, MAX_RADIUS, MIN_RADIUS,
//   gCtx, renderTextMask, drawMeshGradientPreview, generate
// ============================================================

const exportOtfBtn = document.getElementById('export-otf-btn');

// Appends a cubic-bezier circle approximation to an opentype.js Path.
// Uses the standard constant k≈0.5523 for a 4-arc circle.
// Font coordinate space: Y-axis points up.
function addCircleToPath(path, cx, cy, r) {
  const k = 0.5523;
  path.moveTo(cx,         cy + r);
  path.curveTo(cx + k*r, cy + r,  cx + r, cy + k*r,  cx + r, cy);
  path.curveTo(cx + r,   cy - k*r, cx + k*r, cy - r,  cx,     cy - r);
  path.curveTo(cx - k*r, cy - r,  cx - r, cy - k*r,  cx - r, cy);
  path.curveTo(cx - r,   cy + k*r, cx - k*r, cy + r,  cx,     cy + r);
  path.close();
}

// Appends a square (axis-aligned) to an opentype.js Path.
// halfSize is half the side length.
function addSquareToPath(path, cx, cy, halfSize) {
  const s = halfSize;
  path.moveTo(cx - s, cy + s);
  path.lineTo(cx + s, cy + s);
  path.lineTo(cx + s, cy - s);
  path.lineTo(cx - s, cy - s);
  path.close();
}

// Builds and downloads an OTF font containing the 42-character charset.
// Each glyph is built by running the full dot-generation pipeline on a single
// character, then mapping canvas dot positions to font coordinate space.
// Coordinate mapping:
//   fontX = (canvasX - PADDING) * SCALE
//   fontY = (BASELINE_Y - canvasY) * SCALE
// where BASELINE_Y and font metrics are measured at runtime from the canvas API
// to exactly match how the browser renders DINish Bold at FONT_SIZE px.
function exportOTF() {
  exportOtfBtn.textContent = 'En cours...';
  exportOtfBtn.disabled = true;

  // Measure real font metrics from the canvas — avoids hardcoded UFO values
  // that may not match the browser's actual rendering of DINish Bold.
  // textBaseline MUST be 'alphabetic' before measuring: fontBoundingBoxAscent
  // is relative to the current textBaseline, and renderTextMask sets it to 'top'
  // (which would return ~0 and place all glyphs below the baseline).
  const UPM = 1024;
  const measureCtx = hiddenCanvas.getContext('2d');
  measureCtx.font         = `700 ${FONT_SIZE}px DINish, sans-serif`;
  measureCtx.textBaseline = 'alphabetic';
  const measured          = measureCtx.measureText('H');

  // fontBoundingBoxAscent: distance from alphabetic baseline UP to top of em box
  // fontBoundingBoxDescent: distance from alphabetic baseline DOWN to bottom of em box
  // When text is drawn at y=PADDING with textBaseline='top', the top of the em box
  // is at y=PADDING, so the alphabetic baseline = PADDING + fontBoundingBoxAscent.
  const BASELINE_Y = PADDING + measured.fontBoundingBoxAscent;
  const SCALE      = UPM / FONT_SIZE;  // canvas px → font units
  const ASCENDER   = Math.round(measured.fontBoundingBoxAscent  * SCALE);
  const DESCENDER  = -Math.round(measured.fontBoundingBoxDescent * SCALE);

  // Advance widths (font units) extracted from DINish-Bold UFO glif files
  const ADVANCE_WIDTHS = {
    'A':620, 'B':612, 'C':614, 'D':614, 'E':569, 'F':569, 'G':614, 'H':623,
    'I':254, 'J':338, 'K':624, 'L':528, 'M':771, 'N':649, 'O':614, 'P':580,
    'Q':614, 'R':614, 'S':561, 'T':528, 'U':628, 'V':567, 'W':852, 'X':607,
    'Y':553, 'Z':517,
    '0':524, '1':356, '2':504, '3':516, '4':533, '5':508, '6':528, '7':467,
    '8':537, '9':528,
    '.':220, '?':461, ':':220, ',':197, ';':220, '!':254
  };

  // PostScript glyph names for non-letter characters
  const GLYPH_NAMES = {
    '0':'zero',  '1':'one',   '2':'two',   '3':'three', '4':'four',
    '5':'five',  '6':'six',   '7':'seven', '8':'eight', '9':'nine',
    '.':'period', '?':'question', ':':'colon', ',':'comma', ';':'semicolon', '!':'exclam'
  };

  const CHARSET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.:?,;!';
  const glyphs  = [];

  // .notdef — required as the first glyph in any valid OTF
  glyphs.push(new opentype.Glyph({
    name: '.notdef', unicode: 0, advanceWidth: 500, path: new opentype.Path()
  }));

  // space — gives kerning/layout tools a working word-break glyph
  glyphs.push(new opentype.Glyph({
    name: 'space', unicode: 32, advanceWidth: 222, path: new opentype.Path()
  }));

  // One glyph per charset character
  for (const char of CHARSET) {
    // Run the full render pipeline for this single character
    const { canvasW, canvasH } = renderTextMask(char);
    drawMeshGradientPreview(canvasW, canvasH);

    const step      = DOT_SPACING * tailleGenerationMultiplier;
    const imageData = gCtx.getImageData(0, 0, canvasW, canvasH);
    const pixels    = imageData.data;
    const path      = new opentype.Path();

    for (let y = step / 2; y < canvasH; y += step) {
      for (let x = step / 2; x < canvasW; x += step) {
        const i          = (Math.floor(y) * canvasW + Math.floor(x)) * 4;
        const brightness = (pixels[i] + pixels[i+1] + pixels[i+2]) / 3;
        if (brightness >= 245) continue;

        // Apply the same probabilistic filter as the SVG output
        const probability = Math.max(0, 1 - (brightness / 204) * presenceStrength * 2);
        if (Math.random() > probability) continue;

        const darkness = Math.max(0, 1 - brightness / 204);
        const radius   = (MIN_RADIUS + darkness * (MAX_RADIUS - MIN_RADIUS)) * sizeMultiplier * tailleGenerationMultiplier;

        // Map canvas px → font units, flipping Y axis
        const fx = (x - PADDING) * SCALE;
        const fy = (BASELINE_Y - y) * SCALE;
        const fr = radius * SCALE;

        if (currentShape === 'square') {
          addSquareToPath(path, fx, fy, fr);
        } else {
          // circle, darkblue_circle, star (and any future shapes) → circle
          addCircleToPath(path, fx, fy, fr);
        }
      }
    }

    const name = GLYPH_NAMES[char] || char;
    glyphs.push(new opentype.Glyph({
      name,
      unicode:      char.codePointAt(0),
      advanceWidth: ADVANCE_WIDTHS[char] || 500,
      path
    }));
  }

  const font = new opentype.Font({
    familyName:  'DottFont',
    styleName:   'Regular',
    unitsPerEm:  UPM,
    ascender:    ASCENDER,
    descender:   DESCENDER,
    glyphs
  });

  // Build filename from current settings: shape_tailleGeneration_size_presence
  const filename = `${currentShape}_${tailleGenerationMultiplier.toFixed(2)}_${sizeMultiplier.toFixed(2)}_${presenceStrength.toFixed(2)}.otf`;
  font.download(filename);

  // Restore the display to the current text input after processing
  generate();
  exportOtfBtn.textContent = 'Exporter OTF';
  exportOtfBtn.disabled = false;
}

// OTF export button — builds the full 42-char font on click
exportOtfBtn.addEventListener('click', exportOTF);
