// ============================================================
// OTF Export — DottFont Generator
//
// Builds and downloads a .otf font file containing all characters
// defined in dinish-bold-metrics.json, using opentype.js.
//
// Each glyph is generated by running the full dot-generation pipeline
// (renderTextMask + drawMeshGradientPreview) on a single character,
// then mapping canvas dot positions to font coordinate space.
//
// Font metrics (UPM, ascender, descender) and per-glyph advance widths
// are read from dinish-bold-metrics.json. BASELINE_Y is still measured
// from the canvas at runtime to match the browser's actual rendering.
//
// Coordinate mapping:
//   fontX = (canvasX - PADDING) * SCALE
//   fontY = (BASELINE_Y - canvasY) * SCALE
//
// Depends on globals from script-generator_DottFont.js:
//   presenceStrength, sizeMultiplier, tailleGenerationMultiplier,
//   currentShape, DOT_SPACING, PADDING, FONT_SIZE, MAX_RADIUS, MIN_RADIUS,
//   gCtx, renderTextMask, drawMeshGradientPreview, generate
// ============================================================

const exportOtfBtn = document.getElementById('export-otf-btn');

// Appends a cubic-bezier circle approximation to an opentype.js Path.
// Uses the standard constant k≈0.5523 for a 4-arc circle.
// Font coordinate space: Y-axis points up.
function addCircleToPath(path, cx, cy, r) {
  const k = 0.5523;
  path.moveTo(cx,         cy + r);
  path.curveTo(cx + k*r, cy + r,  cx + r, cy + k*r,  cx + r, cy);
  path.curveTo(cx + r,   cy - k*r, cx + k*r, cy - r,  cx,     cy - r);
  path.curveTo(cx - k*r, cy - r,  cx - r, cy - k*r,  cx - r, cy);
  path.curveTo(cx - r,   cy + k*r, cx - k*r, cy + r,  cx,     cy + r);
  path.close();
}

// Appends a square (axis-aligned) to an opentype.js Path.
// halfSize is half the side length.
function addSquareToPath(path, cx, cy, halfSize) {
  const s = halfSize;
  path.moveTo(cx - s, cy + s);
  path.lineTo(cx + s, cy + s);
  path.lineTo(cx + s, cy - s);
  path.lineTo(cx - s, cy - s);
  path.close();
}

// Builds and downloads an OTF font for all characters defined in
// dinish-bold-metrics.json. Font metrics and advance widths come from
// the JSON; BASELINE_Y is measured from the canvas at runtime.
async function exportOTF() {
  exportOtfBtn.textContent = 'En cours...';
  exportOtfBtn.disabled = true;

  // Load font metrics and glyph data from JSON.
  // Provides UPM, ascender, descender, and per-glyph advance widths.
  let metrics;
  try {
    const res = await fetch('source_export_otf/dinish-bold-metrics.json');
    metrics = await res.json();
  } catch (e) {
    console.error('Failed to load dinish-bold-metrics.json:', e);
    exportOtfBtn.textContent = 'Erreur JSON';
    exportOtfBtn.disabled = false;
    return;
  }

  const UPM       = metrics.units.upm;
  const ASCENDER  = metrics.fontMetrics.ascender;
  const DESCENDER = metrics.fontMetrics.descender;

  // Measure the alphabetic baseline position in canvas pixels.
  // Strategy: measure 'A' with textBaseline='top' (same as renderTextMask) and use
  // actualBoundingBoxDescent. Since 'A' has yMin=0 (sits exactly on the alphabetic
  // baseline), actualBoundingBoxDescent = distance from the 'top' reference point
  // down to the baseline. This value is always positive and consistent across browsers.
  //
  // Why not fontBoundingBoxAscent? Returns the font-wide ascender (≈1050/1024*px),
  // which is larger than the actual 'top'-to-baseline distance → glyphs shift +211u.
  // Why not alphabeticBaseline? The Canvas spec uses upward-positive convention, so
  // alphabeticBaseline with textBaseline='top' returns a negative number in Chrome/FF
  // → BASELINE_Y = PADDING + negative = too small → glyphs shift into negative y.
  const measureCtx = hiddenCanvas.getContext('2d');
  measureCtx.font         = `700 ${FONT_SIZE}px DINish, sans-serif`;
  measureCtx.textBaseline = 'top';
  const measured   = measureCtx.measureText('A');
  const BASELINE_Y = PADDING + measured.actualBoundingBoxDescent;
  const SCALE      = UPM / FONT_SIZE;  // canvas px → font units

  // Charset is driven by the JSON — only characters with defined metrics are exported.
  const CHARSET = Object.keys(metrics.glyphs);

  // PostScript glyph names for digits and punctuation.
  // Letters use the character itself as the PostScript name.
  const GLYPH_NAMES = {
    '0':'zero',  '1':'one',   '2':'two',   '3':'three', '4':'four',
    '5':'five',  '6':'six',   '7':'seven', '8':'eight', '9':'nine',
    '.':'period', '?':'question', ':':'colon', ',':'comma', ';':'semicolon', '!':'exclam'
  };

  const glyphs = [];

  // .notdef — required as the first glyph in any valid OTF
  glyphs.push(new opentype.Glyph({
    name: '.notdef', unicode: 0, advanceWidth: 500, path: new opentype.Path()
  }));

  // space — gives kerning/layout tools a working word-break glyph
  glyphs.push(new opentype.Glyph({
    name: 'space', unicode: 32, advanceWidth: 222, path: new opentype.Path()
  }));

  // One glyph per character present in the JSON
  for (const char of CHARSET) {
    // Run the full render pipeline for this single character
    const { canvasW, canvasH } = renderTextMask(char);
    drawMeshGradientPreview(canvasW, canvasH);

    const step      = DOT_SPACING * tailleGenerationMultiplier;
    const imageData = gCtx.getImageData(0, 0, canvasW, canvasH);
    const pixels    = imageData.data;
    const path      = new opentype.Path();

    for (let y = step / 2; y < canvasH; y += step) {
      for (let x = step / 2; x < canvasW; x += step) {
        const i          = (Math.floor(y) * canvasW + Math.floor(x)) * 4;
        const brightness = (pixels[i] + pixels[i+1] + pixels[i+2]) / 3;
        if (brightness >= 245) continue;

        // Apply the same probabilistic filter as the SVG output
        const probability = Math.max(0, 1 - (brightness / 204) * presenceStrength * 2);
        if (Math.random() > probability) continue;

        const darkness = Math.max(0, 1 - brightness / 204);
        const radius   = (MIN_RADIUS + darkness * (MAX_RADIUS - MIN_RADIUS)) * sizeMultiplier * tailleGenerationMultiplier;

        // Map canvas px → font units, flipping Y axis
        const fx = (x - PADDING) * SCALE;
        const fy = (BASELINE_Y - y) * SCALE;
        const fr = radius * SCALE;

        if (currentShape === 'square') {
          addSquareToPath(path, fx, fy, fr);
        } else {
          // circle, darkblue_circle, star → circle approximation
          addCircleToPath(path, fx, fy, fr);
        }
      }
    }

    const name = GLYPH_NAMES[char] || char;
    glyphs.push(new opentype.Glyph({
      name,
      unicode:      char.codePointAt(0),
      advanceWidth: metrics.glyphs[char].advanceWidth,
      path
    }));
  }

  const font = new opentype.Font({
    familyName:  'DottFont',
    styleName:   'Regular',
    unitsPerEm:  UPM,
    ascender:    ASCENDER,
    descender:   DESCENDER,
    glyphs
  });

  // Build filename from current settings: shape_tailleGeneration_size_presence
  const filename = `${currentShape}_${tailleGenerationMultiplier.toFixed(2)}_${sizeMultiplier.toFixed(2)}_${presenceStrength.toFixed(2)}.otf`;
  font.download(filename);

  // Restore the display to the current text input after processing
  generate();
  exportOtfBtn.textContent = 'Exporter OTF';
  exportOtfBtn.disabled = false;
}

// OTF export button — builds the font on click
exportOtfBtn.addEventListener('click', exportOTF);
